name: leichtesprache-app

services:
  app:
    build: .
    image: leichtesprache-app-cloud
    container_name: leichtesprache-app-cloud
    ports:
      - "7860:7860" #  Access locally on http://localhost:7860
    network_mode: "host"  # Allows the container to access Ollama running on the host
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
