services:
  app:
    build: .
    volumes:
      - ./exports:/app/exports
    network_mode: "host"  # Allows the container to access Ollama running on the host
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
